services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        value: ${DB_HOST}

      - key: DB_POSTGRESDB_PORT
        value: ${DB_PORT}

      - key: DB_POSTGRESDB_DATABASE
        value: ${DB_NAME}

      - key: DB_POSTGRESDB_USER
        value: ${DB_USER}

      - key: DB_POSTGRESDB_PASSWORD
        value: ${DB_PASSWORD}

      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
        
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
        
      - key: N8N_RUNNERS_ENABLED
        value: "true"
        
      - key: NODE_OPTIONS
        value: "--max-old-space-size=256"
        
      - key: N8N_METRICS
        value: "false"
        
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
        
      - key: N8N_LOG_LEVEL
        value: "warn"
